// generate.ts — Write .claude/ directory into a project

import { mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import type { DetectedTech } from './detect.js';
import { selectFiles } from './registry.js';

interface GenerateOptions {
  projectDir: string;
  detected: DetectedTech[];
  includeAgents: boolean;
}

interface GenerateResult {
  fileCount: number;
  files: string[];
}

function generateClaudeMd(detected: DetectedTech[], skillPaths: string[]): string {
  const skillNames = skillPaths
    .filter(p => p.includes('skills/'))
    .map(p => p.split('skills/')[1].split('/')[0]);
  const agentNames = skillPaths
    .filter(p => p.includes('agents/'))
    .map(p => p.split('agents/')[1].replace('.md', ''));

  const stackLine = detected.length > 0
    ? detected.join(', ')
    : 'generic project';

  return `# Project — Claude Code Context

> Read this file fully before writing any code.
> Skills in \`.claude/skills/\` load automatically when relevant.
> Agents in \`.claude/agents/\` are available for specialized tasks.

## Project Overview

**Detected stack:** ${stackLine}

<!-- 
  Fill in the sections below to give Claude more context about your project.
  The more detail you add, the better Claude Code performs.
-->

## Architecture

<!-- Describe how the system is structured (frontend, backend, services, DB) -->

## Data Model

<!-- Key entities and their relationships -->

## Conventions

<!-- Project-specific coding conventions, naming, folder structure -->

## Available Skills
${skillNames.length > 0
    ? skillNames.map(n => `- \`${n}\``).join('\n')
    : '- (none detected — add your stack and re-run contextkit)'}

## Available Agents
${agentNames.length > 0
    ? agentNames.map(n => `- \`${n}\``).join('\n')
    : '- (none)'}

---

*Generated by [ContextKit](https://github.com/strifero/ContextKit) — by [Strife Technologies](https://strifetech.com)*
`;
}

export async function generateFiles(opts: GenerateOptions): Promise<GenerateResult> {
  const { projectDir, detected, includeAgents } = opts;
  const claudeDir = join(projectDir, '.claude');
  const writtenFiles: string[] = [];

  const skillFiles = selectFiles(detected, includeAgents);

  // Write each skill/agent file
  for (const file of skillFiles) {
    const fullPath = join(claudeDir, file.path);
    const dir = dirname(fullPath);
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    writeFileSync(fullPath, file.content, 'utf-8');
    writtenFiles.push(`.claude/${file.path}`);
  }

  // Write CLAUDE.md
  const claudeMdPath = join(claudeDir, 'CLAUDE.md');
  if (!existsSync(claudeDir)) mkdirSync(claudeDir, { recursive: true });
  writeFileSync(claudeMdPath, generateClaudeMd(detected, skillFiles.map(f => f.path)), 'utf-8');
  writtenFiles.unshift('.claude/CLAUDE.md');

  return { fileCount: writtenFiles.length, files: writtenFiles };
}
